version: "3.9"

services:
  web:
    build: .
    container_name: django_anime_service_web
    command: bash entrypoint.sh
    restart: always
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
      - log:/app/log
    ports:
      - "8000:8000"
    env_file: .env.docker
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    container_name: django_anime_service_redis
    command: redis-server --requirepass yourpassword
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - "6379:6379"
    depends_on:
      - database

  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: django_anime_service_database
    ports:
      - "5432:5432"
    env_file: .env.docker

  worker:
    build: .
    container_name: django_anime_service_worker
    command: celery -A config worker -l info
    env_file: .env.docker
    volumes:
      - media:/app/media
      - log:/app/log
    depends_on:
      - nginx

  beat:
    build: .
    container_name: django_anime_service_beat
    command: celery -A config beat -l info
    env_file: .env.docker
    volumes:
      - media:/app/media
      - log:/app/log
    depends_on:
      - worker

  nginx:
    build: ./nginx
    container_name: django_anime_service_nginx
    restart: on-failure
    ports:
      - "80:80"
    env_file: .env.docker
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
  log:
  redis:
