version: "3.9"

services:
  redis:
    image: redis
    container_name: django_anime_service_redis
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file:
      - ./.env
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - "6379:6379"
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: django_anime_service_database
    ports:
      - "5432:5432"
    env_file: .env


volumes:
  postgres_data:
  redis:
