# Generated by Django 4.0.5 on 2022-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcollbackmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
