# Generated by Django 4.0.5 on 2022-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botcollbackmessage_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.CharField(max_length=255, verbose_name='ID telegram')),
                ('id_anime', models.IntegerField(verbose_name='ID anime')),
            ],
        ),
    ]
