# Generated by Django 4.0.5 on 2022-08-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botidimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotIdImage',
        ),
    ]
