# Generated by Django 4.0.5 on 2022-09-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('anime', '0027_anime_telegram_id_file'),
        ('bot', '0005_botuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUserAnimePeriodTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('period_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='anime',
        ),
        migrations.AddField(
            model_name='botuser',
            name='track',
            field=models.ManyToManyField(blank=True, through='bot.BotUserAnimePeriodTask', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='botuseranimeperiodtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser'),
        ),
    ]
