# Generated by Django 4.0.5 on 2022-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_botuseranimeperiodtask_remove_botuser_anime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='ChatID пользователя telegram'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='ID пользователя telegram'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
