# Generated by Django 4.0.5 on 2022-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_botuser_chat_id_alter_botuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
