# Generated by Django 4.0.5 on 2023-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_botuser_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('chat_id', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
