# Generated by Django 4.0.5 on 2023-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='screen_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('preview', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeVost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anime', models.IntegerField(unique=True)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('url_image_preview', models.ImageField(blank=True, null=True, upload_to='preview/')),
                ('year', models.CharField(blank=True, max_length=20)),
                ('timer', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('day_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=None, null=True)),
                ('anons', models.BooleanField(default=False)),
                ('indefinite_exit', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anime_composed', models.ManyToManyField(blank=True, to='anime.animevost')),
                ('genre', models.ManyToManyField(blank=True, related_name='genres', to='anime.genre')),
                ('screen_image', models.ManyToManyField(blank=True, related_name='screen_images', to='anime.screenimages')),
                ('series', models.ManyToManyField(blank=True, related_name='anime', to='anime.series')),
            ],
        ),
    ]
