# Generated by Django 4.0.5 on 2024-01-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='screenimages',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='screenimages',
            name='project_anime',
        ),
        migrations.RemoveField(
            model_name='series',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='project_anime',
        ),
        migrations.AddField(
            model_name='screenimages',
            name='animevost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_images', to='anime.animevost'),
        ),
        migrations.AddField(
            model_name='screenimages',
            name='poster',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('original', 'Original')], default='original', max_length=8),
        ),
        migrations.AddField(
            model_name='series',
            name='animevost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_series', to='anime.animevost'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.ManyToManyField(blank=True, related_name='decor', to='anime.person')),
                ('editing', models.ManyToManyField(blank=True, related_name='editing', to='anime.person')),
                ('timing', models.ManyToManyField(blank=True, related_name='timing', to='anime.person')),
                ('translator', models.ManyToManyField(blank=True, related_name='translator', to='anime.person')),
                ('voice', models.ManyToManyField(blank=True, related_name='voice', to='anime.person')),
            ],
        ),
        migrations.CreateModel(
            name='AniLibria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_alternative', models.CharField(blank=True, max_length=255, null=True)),
                ('announce', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Completed'), (3, 'Is hidden'), (4, 'Un ongoing')])),
                ('updated', models.DateTimeField(blank=True, help_text='Last tile update (Usually the title is updated when new releases are released)', null=True)),
                ('last_change', models.DateTimeField(blank=True, help_text='Last title change (For example, a description or announcement)', null=True)),
                ('anime_type', models.IntegerField(choices=[(0, 'Movie'), (1, 'TV'), (2, 'OVA'), (3, 'ONA'), (4, 'Special'), (5, 'WEB')])),
                ('season', models.IntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')])),
                ('week_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('description', models.TextField()),
                ('in_favorites', models.IntegerField()),
                ('blocked', models.BooleanField(default=False, help_text='The title is blocked in the Russian Federation')),
                ('bakanim', models.BooleanField(default=False, help_text='Title blocked due to Wakanim complaints')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='anilibria', to='anime.genre')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anilibria', to='anime.team')),
            ],
        ),
        migrations.AddField(
            model_name='screenimages',
            name='anilibria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_images', to='anime.anilibria'),
        ),
        migrations.AddField(
            model_name='series',
            name='anilibria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_series', to='anime.anilibria'),
        ),
    ]
