# Generated by Django 4.0.5 on 2022-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='day_week',
            field=models.CharField(default='', max_length=20, verbose_name='День недели'),
        ),
    ]
