# Generated by Django 4.0.5 on 2023-09-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_animevost_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animevost',
            old_name='id_anime',
            new_name='anime_id',
        ),
    ]
