# Generated by Django 4.0.5 on 2022-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_day_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='screen_image',
            field=models.ManyToManyField(related_name='screen_images', to='anime.screenimages'),
        ),
    ]
