# Generated by Django 4.0.5 on 2023-09-17 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_id_anime_animevost_anime_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
