# Generated by Django 4.0.5 on 2022-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_screen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_composed',
            field=models.ManyToManyField(blank=True, related_name='anime_composeds', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='screen_image',
            field=models.ManyToManyField(blank=True, related_name='screen_images', to='anime.screenimages'),
        ),
    ]
