# Generated by Django 4.0.5 on 2023-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_animevost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='animevost',
            name='anons_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
