# Generated by Django 4.0.5 on 2022-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_anime_composed_alter_anime_screen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='id_anime',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID animevost'),
            preserve_default=False,
        ),
    ]
