# Generated by Django 4.0.5 on 2022-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_series_id_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Названия'),
        ),
    ]
