# Generated by Django 4.0.5 on 2022-07-15 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0008_series_number_alter_series_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('schedule', 'Запись аниме расписания'), ('anons', 'Запись аниме анонсов'), ('delete', 'Удаления всех записей таблиц (Anime, ScreenImages, Genre)'), ('schedule_update', 'Обновить аниме расписания'), ('anons_update', 'Обновить аниме анонсов'), ('series', 'Запись аниме расписания'), ('series_update', 'Обновления серий'), ('delete_series', 'Очистка данных таблицы Series')], max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
