# Generated by Django 4.0.5 on 2022-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='url_image_preview_s',
            field=models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='Preview изображения [сервер]'),
        ),
        migrations.AddField(
            model_name='screenimages',
            name='images_s',
            field=models.ImageField(blank=True, null=True, upload_to='screen_images/', verbose_name='Скрин [сервер]'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='day_week',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Тип'),
        ),
    ]
