# Generated by Django 4.0.5 on 2022-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_url_image_preview_s_screenimages_images_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='message',
            field=models.CharField(choices=[('schedule', 'Запись аниме расписания'), ('anons', 'Запись аниме анонсов'), ('delete', 'Удаления всех записей таблиц Anime'), ('schedule_update', 'Обновить аниме расписания'), ('anons_update', 'Обновить аниме анонсов'), ('series', 'Запись аниме расписания'), ('series_update', 'Обновления серий'), ('delete_series', 'Очистка данных таблицы Series')], max_length=16),
        ),
    ]
