# Generated by Django 4.0.5 on 2022-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_statistics_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
