# Generated by Django 4.0.5 on 2022-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_alter_statistics_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genres', to='anime.genre'),
        ),
    ]
