# Generated by Django 4.0.5 on 2022-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='day_week',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='День недели'),
        ),
    ]
