# Generated by Django 4.0.5 on 2022-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_alter_anime_day_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='id пользователя')),
                ('action', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
