# Generated by Django 4.0.5 on 2022-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_botstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCollBackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='id пользователя')),
                ('message', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
