# Generated by Django 4.0.5 on 2022-08-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_botcollbackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcollbackmessage',
            name='read',
            field=models.BooleanField(default=True, verbose_name='Прочитано'),
        ),
    ]
