# Generated by Django 4.0.5 on 2022-08-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_botcollbackmessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcollbackmessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
