# Generated by Django 4.0.5 on 2022-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0021_anime_indefinite_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка animevost'),
        ),
    ]
