# Generated by Django 4.0.5 on 2022-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0022_alter_anime_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='indefinite_exit',
            field=models.BooleanField(default=False, verbose_name='Неопределенная дата выход'),
        ),
    ]
