# Generated by Django 4.0.5 on 2022-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_alter_anime_indefinite_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Режиссёр'),
        ),
    ]
