# Generated by Django 4.0.5 on 2022-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0024_alter_anime_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
