# Generated by Django 4.0.5 on 2022-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_delete_botcollbackmessage_delete_botstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='telegram_id_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID картинки на сервере телеграм'),
        ),
    ]
