# Generated by Django 4.0.5 on 2023-02-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0027_anime_telegram_id_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_task', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
