# Generated by Django 4.0.5 on 2023-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0028_animesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='animesettings',
            name='send_images_telegram',
            field=models.BooleanField(default=False, verbose_name='Отправлять изображения на сервер telegram'),
        ),
        migrations.AlterField(
            model_name='animesettings',
            name='status_task',
            field=models.BooleanField(default=True, verbose_name='Авто обновления'),
        ),
    ]
