# Generated by Django 4.0.5 on 2023-03-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0029_animesettings_send_images_telegram_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
