# Generated by Django 4.0.5 on 2023-04-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0030_delete_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='url_image_preview_s',
        ),
        migrations.RemoveField(
            model_name='screenimages',
            name='images_s',
        ),
        migrations.AlterField(
            model_name='anime',
            name='url_image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='Preview изображения [сервер]'),
        ),
        migrations.AlterField(
            model_name='screenimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='screen_images/', verbose_name='Скрин [сервер]'),
        ),
    ]
