# Generated by Django 4.0.5 on 2023-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0031_remove_anime_url_image_preview_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='hd',
        ),
        migrations.RemoveField(
            model_name='series',
            name='std',
        ),
        migrations.AddField(
            model_name='series',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на серию'),
        ),
        migrations.AddField(
            model_name='series',
            name='preview',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображения предпросмотра'),
        ),
        migrations.AddField(
            model_name='series',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер'),
        ),
    ]
