# Generated by Django 4.0.5 on 2023-04-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0032_remove_series_hd_remove_series_std_series_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animesettings',
            name='send_images_telegram',
        ),
    ]
