# Generated by Django 4.0.5 on 2023-04-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0033_remove_animesettings_send_images_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='telegram_id_file',
        ),
    ]
